name: Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
      - branch-* # Matches all branches starting with 'branch-'
  pull_request:
    types: [opened, synchronize, reopened] # Removed 'closed' to avoid redundant PR checks

jobs:
  sonarcloud:
    name: SonarCloud PR Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sonar-cloud # Ensure this directory is correct
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Full clone to avoid shallow clone issues with Sonar
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ensure you're using a supported Node.js version

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test -- --coverage # Run tests with coverage, necessary for SonarCloud

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.sources=src # Ensure correct path to your source files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token to fetch PR details
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # SonarCloud token for authentication

  merge-analysis:
    name: SonarCloud Analysis on PR Merge
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization
            -Dsonar.branch.name=main # Change branch to main after PR is merged
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
